import 'package:file_selector/file_selector.dart';
import 'package:flutter/services.dart';
import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:panes/panes.dart';
import 'package:re_editor/re_editor.dart';
import 'package:re_highlight/languages/sql.dart';
import 'package:re_highlight/styles/atom-one-dark.dart';

import '../../../domain/sql/sql_statement_splitter.dart';
import '../search/search_providers.dart';
import '../settings/settings_providers.dart';
import 'editor_find_panel.dart';
import 'result_grid.dart';
import 'worksheet_providers.dart';
import 'worksheet_state.dart';

// Clean Dev-Tool tokens (ADR-0007/theming #7) — inline until ui/core/theme lands.
const _bg = Color(0xFF0D0E11);
const _panel = Color(0xFF16181D);
const _hair = Color(0xFF262A31);
const _accent = Color(0xFF2FE6FF);
const _textMid = Color(0xFF9BA1AD);
const _err = Color(0xFFFF6B6B);
const _ok = Color(0xFF6FE39A);

/// The query workspace: `re_editor` (top) + `pluto_grid` (bottom) in a resizable
/// vertical `MultiPane`, driven by [worksheetProvider]. First end-to-end slice
/// of connect → query → grid (issues #12/#15).
class WorksheetView extends ConsumerStatefulWidget {
  const WorksheetView({super.key, required this.worksheetId});

  final String worksheetId;

  @override
  ConsumerState<WorksheetView> createState() => _WorksheetViewState();
}

class _WorksheetViewState extends ConsumerState<WorksheetView> {
  late final CodeLineEditingController _code;
  final _panes = PaneController(
    entries: [
      PaneEntry(id: 'editor', initialSize: PaneSize.fraction(0.42)),
      PaneEntry(id: 'result', initialSize: PaneSize.fraction(0.58)),
    ],
  );

  @override
  void initState() {
    super.initState();
    // A tab opened from the sidebar carries a seed query; else the default.
    final seed = ref.read(worksheetSeedsProvider)[widget.worksheetId];
    _code = CodeLineEditingController.fromText(
        seed?.sql ?? 'SELECT * FROM customers;');
    // Publish the selection so Search Everything can open pre-filled with the
    // identifier you just highlighted. Filtered to short single-line text by
    // the provider — selecting a whole query means you want to search, not to
    // look that statement up as a name.
    _code.addListener(_publishSelection);
    if (seed != null) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (!mounted) return;
        ref.read(worksheetSeedsProvider.notifier).take(widget.worksheetId);
        // "Preview data" runs on open; "Open in editor" just loads the SQL.
        if (seed.autoRun) {
          ref.read(worksheetProvider(widget.worksheetId).notifier).run(seed.sql);
        }
      });
    }
  }

  @override
  void dispose() {
    _code.removeListener(_publishSelection);
    _code.dispose();
    super.dispose();
  }

  void _publishSelection() {
    if (!mounted) return;
    ref.read(editorSelectionProvider.notifier).set(_code.selectedText);
  }

  // ⌃⏎ chaining works without editor focus now that Run is an app-wide shortcut
  // (see AppShell → WorksheetCommands). Returning caret focus after a run so you
  // can keep *typing* is still open (a naive requestFocus fought the grid).
  void _runSql(String sql) =>
      ref.read(worksheetProvider(widget.worksheetId).notifier).run(sql);

  /// Run the whole editor buffer (▶ Run). Also the sidebar's request path.
  void _run() => _runSql(_code.text);

  /// Run just the selected SQL, if any.
  void _runSelection() {
    if (_code.selectedText.trim().isNotEmpty) _runSql(_code.selectedText);
  }

  /// Run the single statement under the caret (dialect-aware split).
  void _runAtCursor() {
    final engine = ref.read(currentConnectionProvider).engine;
    final st = SqlStatementSplitter(SqlDialect.of(engine))
        .statementAt(_code.text, _caretOffset());
    if (st != null) _runSql(st.sql);
  }

  /// Ctrl/⌘+Enter: run the selection if there is one, else the statement at the
  /// caret — the DataGrip/DBeaver default.
  void _runSmart() =>
      _code.selectedText.trim().isNotEmpty ? _runSelection() : _runAtCursor();

  /// Absolute char offset of the caret in the full buffer (re_editor gives it as
  /// line + column).
  int _caretOffset() {
    final sel = _code.selection;
    final lines = _code.text.split('\n');
    final line = sel.extentIndex.clamp(0, lines.length - 1);
    var off = 0;
    for (var i = 0; i < line; i++) {
      off += lines[i].length + 1; // + newline
    }
    return off + sel.extentOffset;
  }

  @override
  Widget build(BuildContext context) {
    final result = ref.watch(worksheetProvider(widget.worksheetId));
    final connName = ref.watch(currentConnectionProvider).name;
    // Sidebar can request a query — only the *active* worksheet responds.
    // The sidebar/history can load a query into the *active* worksheet. It is
    // deliberately NOT run: history now contains the UPDATEs generated by grid
    // edits, and re-executing one on a click would be destructive. The user
    // presses Run when they mean it.
    ref.listen<QueryRequest?>(requestedQueryProvider, (_, next) {
      final isActive =
          ref.read(worksheetTabsProvider).activeId == widget.worksheetId;
      if (next != null && isActive) {
        _code.text = next.sql;
        if (next.run) _run();
        ref.read(requestedQueryProvider.notifier).clear();
      }
    });
    // Menu-bar / global-shortcut commands go to the active worksheet.
    ref.listen<WorksheetCommandEvent?>(worksheetCommandsProvider, (_, e) {
      if (e == null) return;
      if (ref.read(worksheetTabsProvider).activeId != widget.worksheetId) return;
      switch (e.command) {
        case WorksheetCommand.runSmart:
          _runSmart();
        case WorksheetCommand.runWhole:
          _run();
        case WorksheetCommand.runAtCursor:
          _runAtCursor();
        case WorksheetCommand.runSelection:
          _runSelection();
        case WorksheetCommand.cancel:
          ref.read(worksheetProvider(widget.worksheetId).notifier).cancel();
      }
    });
    return Container(
      color: _bg,
      child: MultiPane(
        direction: Axis.vertical,
        controller: _panes,
        paneBuilder: (context, id, _) => switch (id) {
          'editor' => _editorPane(connName),
          'result' => _ResultPane(
            result: result,
            worksheetId: widget.worksheetId,
          ),
          _ => const SizedBox.shrink(),
        },
      ),
    );
  }

  Future<void> _openFile() async {
    const group = XTypeGroup(
      label: 'SQLite',
      extensions: ['db', 'sqlite', 'sqlite3'],
    );
    final file = await openFile(acceptedTypeGroups: const [group]);
    if (file != null && mounted) {
      ref.read(currentConnectionProvider.notifier).openFile(file.path);
    }
  }

  Widget _editorPane(String connName) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _toolbar(connName),
        Expanded(
          // ⌃⏎ is handled app-wide at the shell (survives focus leaving the
          // editor after a run); the editor's own newLine binding drops ⌃⏎ so it
          // bubbles up (see _SqlEditorShortcuts).
          child: CodeEditor(
            controller: _code,
            shortcutsActivatorsBuilder: const _SqlEditorShortcuts(),
            // Ctrl+F was already bound by re_editor; without a builder there
            // was simply no panel for it to show.
            findBuilder: (context, controller, readOnly) =>
                EditorFindPanel(controller: controller, readOnly: readOnly),
            style: CodeEditorStyle(
              fontSize: ref.watch(settingsProvider).editorFontSize,
              fontFamily: ref.watch(settingsProvider).editorFontFamily,
              backgroundColor: _bg,
              codeTheme: CodeHighlightTheme(
                languages: {'sql': CodeHighlightThemeMode(mode: langSql)},
                theme: atomOneDarkTheme,
              ),
            ),
          ),
        ),
      ],
    );
  }

  /// Manual-commit toggle + (when on) Commit / Rollback. Commit/Rollback enable
  /// only while a transaction is open.
  List<Widget> _txControls() {
    final manual = ref.watch(manualCommitProvider(widget.worksheetId));
    final txOpen = ref.watch(worksheetTxProvider(widget.worksheetId));
    final notifier = ref.read(worksheetProvider(widget.worksheetId).notifier);
    return [
      Tooltip(
        message: manual
            ? 'Manual commit: ON (Run opens a transaction)'
            : 'Autocommit (click for manual commit)',
        child: ToggleButton(
          checked: manual,
          onChanged: (_) =>
              ref.read(manualCommitProvider(widget.worksheetId).notifier).toggle(),
          child: const Icon(FluentIcons.database_sync, size: 14),
        ),
      ),
      if (manual) ...[
        const SizedBox(width: 6),
        Button(
          onPressed: txOpen ? notifier.commit : null,
          child: const Text('Commit'),
        ),
        const SizedBox(width: 4),
        Button(
          onPressed: txOpen ? notifier.rollback : null,
          child: const Text('Rollback'),
        ),
      ],
      const SizedBox(width: 10),
    ];
  }

  Widget _continueOnErrorToggle() {
    final on = ref.watch(continueOnErrorProvider);
    return Tooltip(
      message: on
          ? 'Continue on error: ON (script runs past failures)'
          : 'Stop on error (click to continue past failures)',
      child: ToggleButton(
        checked: on,
        onChanged: (v) => ref.read(continueOnErrorProvider.notifier).set(v),
        child: const Icon(FluentIcons.fast_forward, size: 14),
      ),
    );
  }

  Widget _toolbar(String connName) {
    return Container(
      height: 42,
      padding: const EdgeInsets.symmetric(horizontal: 10),
      decoration: const BoxDecoration(
        color: _panel,
        border: Border(bottom: BorderSide(color: _hair)),
      ),
      child: Row(
        children: [
          const Icon(FluentIcons.database, size: 14, color: _accent),
          const SizedBox(width: 6),
          Flexible(
            child: Text(
              '$connName · ${ref.watch(currentConnectionProvider).engine.label}',
              overflow: TextOverflow.ellipsis,
              style: const TextStyle(color: _textMid, fontSize: 12),
            ),
          ),
          const SizedBox(width: 12),
          Button(onPressed: _openFile, child: const Text('Open…')),
          const Spacer(),
          ..._txControls(),
          _continueOnErrorToggle(),
          const SizedBox(width: 10),
          if (ref.watch(worksheetProvider(widget.worksheetId))
              is WorksheetRunning)
            FilledButton(
              onPressed:
                  ref.read(worksheetProvider(widget.worksheetId).notifier).cancel,
              child: const Text('■ Cancel'),
            )
          else
            FilledButton(onPressed: _run, child: const Text('▶ Run')),
          const SizedBox(width: 6),
          DropDownButton(
            title: const Icon(FluentIcons.chevron_down, size: 10),
            items: [
              MenuFlyoutItem(
                leading: const Icon(FluentIcons.caret_right, size: 12),
                text: const Text('Run at cursor   Ctrl+Enter'),
                onPressed: _runAtCursor,
              ),
              MenuFlyoutItem(
                leading: const Icon(FluentIcons.text_field, size: 12),
                text: const Text('Run selection'),
                onPressed: _runSelection,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

/// re_editor's defaults bind **Ctrl+Enter to newline** (which swallowed our Run
/// shortcut — inserting a newline over the selection) and put word move/select
/// on **Alt+Arrow** only. This drops Ctrl+Enter from `newLine` (so ⌃⏎ bubbles to
/// the Run `CallbackShortcuts`) and adds **Ctrl(+Shift)+Arrow** for word
/// move/select alongside the existing Alt bindings (Linux/Windows convention).
class _SqlEditorShortcuts extends CodeShortcutsActivatorsBuilder {
  const _SqlEditorShortcuts();
  static const _base = DefaultCodeShortcutsActivatorsBuilder();

  @override
  List<ShortcutActivator>? build(CodeShortcutType type) => switch (type) {
        CodeShortcutType.newLine => const [
            SingleActivator(LogicalKeyboardKey.enter),
            SingleActivator(LogicalKeyboardKey.enter, shift: true),
            SingleActivator(LogicalKeyboardKey.numpadEnter),
            SingleActivator(LogicalKeyboardKey.numpadEnter, shift: true),
          ],
        CodeShortcutType.cursorMoveWordBoundaryBackward => const [
            SingleActivator(LogicalKeyboardKey.arrowLeft, control: true),
            SingleActivator(LogicalKeyboardKey.arrowLeft, alt: true),
          ],
        CodeShortcutType.cursorMoveWordBoundaryForward => const [
            SingleActivator(LogicalKeyboardKey.arrowRight, control: true),
            SingleActivator(LogicalKeyboardKey.arrowRight, alt: true),
          ],
        // Key→direction kept identical to re_editor's own mapping (only the
        // modifier changes), so behaviour matches the working Alt+Shift+Arrow.
        CodeShortcutType.selectionExtendWordBoundaryForward => const [
            SingleActivator(LogicalKeyboardKey.arrowLeft,
                control: true, shift: true),
            SingleActivator(LogicalKeyboardKey.arrowLeft,
                alt: true, shift: true),
          ],
        CodeShortcutType.selectionExtendWordBoundaryBackward => const [
            SingleActivator(LogicalKeyboardKey.arrowRight,
                control: true, shift: true),
            SingleActivator(LogicalKeyboardKey.arrowRight,
                alt: true, shift: true),
          ],
        _ => _base.build(type),
      };
}

class _ResultPane extends StatelessWidget {
  const _ResultPane({required this.result, required this.worksheetId});
  final WorksheetResult result;
  final String worksheetId;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: _panel,
      child: switch (result) {
        WorksheetIdle() => _centered('Run a query to see results.'),
        WorksheetRunning() => const Center(child: ProgressRing()),
        // A single-statement script renders its one result directly (grid /
        // message / failure); a multi-statement script gets sub-tabs + log.
        WorksheetScript(:final outcomes, :final canceled) =>
          _scriptBody(outcomes, canceled, worksheetId),
        _ => _single(result, worksheetId, 0),
      },
    );
  }
}

Widget _scriptBody(
  List<StatementOutcome> outcomes,
  bool canceled,
  String worksheetId,
) {
  final body = outcomes.isEmpty
      ? _centered('Run canceled before any statement ran.')
      : outcomes.length == 1
          ? _single(outcomes.first.result, worksheetId, 0,
              sql: outcomes.first.sql)
          : _ScriptView(outcomes: outcomes, worksheetId: worksheetId);
  if (!canceled) return body;
  return Column(children: [
    Container(
      width: double.infinity,
      color: const Color(0x22FFB020),
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 5),
      child: const Text('■ Run canceled — remaining statements were not run.',
          style: TextStyle(color: Color(0xFFFFB020), fontSize: 11.5)),
    ),
    Expanded(child: body),
  ]);
}

/// Renders one statement's payload — the original single-result view.
Widget _single(WorksheetResult r, String worksheetId, int gridIndex,
        {String? sql}) =>
    switch (r) {
  WorksheetRows() => ResultGrid(
    rows: r,
    worksheetId: worksheetId,
    gridId: '$worksheetId:$gridIndex:${identityHashCode(r)}',
    sourceSql: sql,
  ),
  WorksheetMessage(:final text) => _banner(
    text,
    color: _ok,
    icon: FluentIcons.check_mark,
  ),
  WorksheetFailure(:final error) => _banner(
    '${error.kind.name}: ${error.message}',
    color: _err,
    icon: FluentIcons.error_badge,
  ),
  _ => _centered('Run a query to see results.'),
};

Widget _centered(String s) => Center(
  child: Text(s, style: const TextStyle(color: _textMid)),
);

Widget _banner(String s, {required Color color, required IconData icon}) {
  return Padding(
    padding: const EdgeInsets.all(14),
    child: Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(icon, color: color, size: 16),
        const SizedBox(width: 8),
        Flexible(
          child: Text(s, style: TextStyle(color: color)),
        ),
      ],
    ),
  );
}

/// Multi-statement result: a result sub-tab per row-returning statement + a
/// Messages tab logging every statement's outcome (ADR-0007 / #15).
class _ScriptView extends StatefulWidget {
  const _ScriptView({required this.outcomes, required this.worksheetId});
  final List<StatementOutcome> outcomes;
  final String worksheetId;

  @override
  State<_ScriptView> createState() => _ScriptViewState();
}

class _ScriptViewState extends State<_ScriptView> {
  int _tab = 0;

  @override
  Widget build(BuildContext context) {
    final rows = [
      for (final o in widget.outcomes)
        if (o.isRows) o,
    ];
    // No grids to show → the log is the whole view.
    if (rows.isEmpty) return _messagesLog(widget.outcomes);

    final labels = [for (final o in rows) 'Result ${o.index}', 'Messages'];
    final views = <Widget>[
      for (final (i, o) in rows.indexed)
        ResultGrid(
          rows: o.result as WorksheetRows,
          worksheetId: widget.worksheetId,
          gridId: '${widget.worksheetId}:$i:'
              '${identityHashCode(o.result)}',
          sourceSql: o.sql,
        ),
      _messagesLog(widget.outcomes),
    ];
    final sel = _tab.clamp(0, views.length - 1);
    return Column(
      children: [
        _tabStrip(labels, sel),
        Expanded(
          child: IndexedStack(index: sel, children: views),
        ),
      ],
    );
  }

  Widget _tabStrip(List<String> labels, int sel) {
    return Container(
      height: 30,
      color: _bg,
      child: Row(
        children: [
          for (var i = 0; i < labels.length; i++)
            HoverButton(
              onPressed: () => setState(() => _tab = i),
              builder: (context, states) {
                final active = i == sel;
                return Container(
                  padding: const EdgeInsets.symmetric(horizontal: 14),
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    border: Border(
                      bottom: BorderSide(
                        color: active ? _accent : Colors.transparent,
                        width: 2,
                      ),
                    ),
                    color: states.isHovered ? _panel : null,
                  ),
                  child: Text(
                    labels[i],
                    style: TextStyle(
                      color: active ? _accent : _textMid,
                      fontSize: 12,
                      fontWeight: active ? FontWeight.w600 : FontWeight.normal,
                    ),
                  ),
                );
              },
            ),
        ],
      ),
    );
  }
}

/// The execution log — one line per statement (status, detail, duration).
Widget _messagesLog(List<StatementOutcome> outcomes) {
  return Container(
    color: _panel,
    child: ListView.builder(
      padding: const EdgeInsets.symmetric(vertical: 6),
      itemCount: outcomes.length,
      itemBuilder: (context, i) => _logRow(outcomes[i]),
    ),
  );
}

Widget _logRow(StatementOutcome o) {
  final (String text, Color color, IconData icon) = switch (o.result) {
    WorksheetRows r => (
      '${r.rows.length} row(s)${r.capped ? ' · capped' : ''} · ${r.durationMs} ms',
      _ok,
      FluentIcons.check_mark,
    ),
    // DDL has no meaningful affected-row count — show a plain OK.
    WorksheetMessage m => (
      o.kind == StatementKind.ddl ? 'OK' : m.text,
      _ok,
      FluentIcons.check_mark,
    ),
    WorksheetFailure f => (
      '${f.error.kind.name}: ${f.error.message}',
      _err,
      FluentIcons.error_badge,
    ),
    _ => ('', _textMid, FluentIcons.info),
  };
  final preview = o.sql.replaceAll(RegExp(r'\s+'), ' ').trim();
  return Padding(
    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 5),
    child: Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Icon(icon, color: color, size: 14),
        const SizedBox(width: 8),
        Text(
          '#${o.index}',
          style: const TextStyle(
            color: _textMid,
            fontSize: 11.5,
            fontFamily: 'monospace',
          ),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(text, style: TextStyle(color: color, fontSize: 12)),
              Text(
                preview,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: const TextStyle(
                  color: _textMid,
                  fontSize: 11,
                  fontFamily: 'monospace',
                ),
              ),
            ],
          ),
        ),
      ],
    ),
  );
}

